// py-spy --native 的符号化复刻：Cython 生成的 C 文件 → .pyx 行号映射 + demangle。
//
// 口径（benfred/py-spy，本轮实读 src/cython.rs 与 README）：
//   - 不开 --native 时只沿 PyFrameObject 的 back 链走，原生帧整段不可见
//   - 开 --native 需要平台支持：Linux(x86-64/ARM/Aarch64) 与 Windows(x86-64)
//     （macOS、FreeBSD、i686 一整列都是空的）
//   - 最好带符号编译；Cython 还要 **生成的 C 文件** 才能还原 .pyx 行号
//   - 标记形如  /* "foo.pyx":123  ，正则 ^\s*/\* "(.+\..+)":([0-9]+)
//   - 查找用 BTreeMap::range(..lineno).next_back()：**严格小于** lineno 的最大键
//   - 键是 **0-based** 行下标；文件末尾插一个 ("", 0) 哨兵，读到它表示 EOF
//   - demangle 逐段剥 `_<长度><名字>`，官方单测给了 4 条向量
package main

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var markerRE = regexp.MustCompile(`^\s*/\* "(.+\..+)":([0-9]+)`)

// SourceMap 对应 cython.rs 的 SourceMap。
type SourceMap struct {
	keys []int    // 0-based 行下标
	line []int    // .pyx 行号
	file []string // .pyx 文件名
}

// NewSourceMap 解析生成的 C 文件内容。
func NewSourceMap(contents string) *SourceMap {
	sm := &SourceMap{}
	lineCount := 0
	for i, ln := range strings.Split(contents, "\n") {
		if m := markerRE.FindStringSubmatch(ln); m != nil {
			n, _ := strconv.Atoi(m[2])
			sm.keys = append(sm.keys, i)
			sm.file = append(sm.file, m[1])
			sm.line = append(sm.line, n)
		}
		lineCount++
	}
	// 哨兵：键 = lineCount+1，值 ("", 0)
	sm.keys = append(sm.keys, lineCount+1)
	sm.file = append(sm.file, "")
	sm.line = append(sm.line, 0)
	return sm
}

// Lookup 对应 range(..lineno).next_back()：严格小于 lineno 的最大键。
func (sm *SourceMap) Lookup(lineno int) (string, int, bool) {
	pos := sort.SearchInts(sm.keys, lineno) - 1
	if pos < 0 {
		return "", 0, false
	}
	if sm.line[pos] == 0 { // EOF 哨兵
		return "", 0, false
	}
	return sm.file[pos], sm.line[pos], true
}

var demanglePrefixes = []string{
	"__pyx_fuse_1_0__pyx_pw", "__pyx_fuse_0__pyx_f", "__pyx_fuse_1__pyx_f",
	"__pyx_pf", "__pyx_pw", "__pyx_f", "___pyx_f", "___pyx_pw",
}

// Demangle 对应 cython.rs 的 demangle。
func Demangle(name string) string {
	var current string
	found := false
	for _, p := range demanglePrefixes {
		if strings.HasPrefix(name, p) {
			current = name[len(p):]
			found = true
			break
		}
	}
	if !found {
		return name
	}
	next := current
	for {
		if !strings.HasPrefix(next, "_") {
			break
		}
		digitIndex := 1
		for _, ch := range next[1:] {
			if ch < '0' || ch > '9' {
				break
			}
			digitIndex++
		}
		if digitIndex == 1 {
			break
		}
		digits, _ := strconv.Atoi(next[1:digitIndex])
		current = next[digitIndex:]
		if digits+digitIndex >= len(current) {
			break
		}
		next = next[digits+digitIndex:]
	}
	return current
}

// IgnoreFrame 是 cython.rs 里的调用胶水名单。
func IgnoreFrame(name string) bool {
	for _, f := range []string{"__Pyx_PyFunction_FastCallDict", "__Pyx_PyObject_CallOneArg",
		"__Pyx_PyObject_Call", "__pyx_FusedFunction_call"} {
		if f == name {
			return true
		}
	}
	return false
}

var nativeSupport = map[[2]string]bool{
	{"Linux", "x86-64"}: true, {"Linux", "ARM"}: true,
	{"Linux", "Aarch64"}: true, {"Windows", "x86-64"}: true,
}

func main() {
	cFile := strings.Join([]string{
		"/* Generated by Cython 3.0.10 */",
		`/* "fast.pyx":10`,
		"static int __pyx_f_4fast_compute(void) {",
		"  int i;",
		`/* "fast.pyx":11`,
		"  for (i = 0; i < 10; i++) {",
		`/* "helpers.pyx":3`,
		"    do_work(i);",
		"  }",
		"}",
	}, "\n")

	sm := NewSourceMap(cFile)
	for _, l := range []int{1, 2, 3, 5, 7, 10, 11, 12} {
		f, n, ok := sm.Lookup(l)
		fmt.Printf("lineno=%d -> %q %d ok=%v\n", l, f, n, ok)
	}

	for _, s := range []string{
		"__pyx_pf_8implicit_4_als_30_least_squares_cg",
		"__pyx_pw_8implicit_4_als_5least_squares_cg",
		"__pyx_fuse_1_0__pyx_pw_8implicit_4_als_31_least_squares_cg",
		"__pyx_f_6mtrand_cont0_array",
		"PyEval_EvalFrameDefault",
	} {
		fmt.Printf("demangle(%s) = %s\n", s, Demangle(s))
	}

	fmt.Println("ignore __pyx_FusedFunction_call:", IgnoreFrame("__pyx_FusedFunction_call"))
	fmt.Println("native on OSX/x86-64:", nativeSupport[[2]string{"OSX", "x86-64"}])
}
