#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""py-spy --native：C/C++/Cython 原生扩展的采样与符号化（对照 benfred/py-spy 源码与 README）

被对照的官方实现（本轮实际读过）：
  * README.md —— `--native` 平台支持表（Linux x86-64/ARM/Aarch64、Windows x86-64 才有）、
    「最好带符号编译」「Cython 需要生成的 C 文件才能还原 .pyx 行号」
  * src/cython.rs —— SourceMap 的标记正则、BTreeMap 的「向前找最近标记」查找、
    EOF 哨兵、ignore_frame 名单、demangle 的官方测试向量

运行：python pyspy_native.py
"""
import bisect
import re

# ------------------------------------------------------ cython.rs: 标记解析

# lazy_static! { static ref RE: Regex = Regex::new(r#"^\s*/\* "(.+\..+)":([0-9]+)"#) }
MARKER_RE = re.compile(r'^\s*/\* "(.+\..+)":([0-9]+)')


class SourceMap:
    """src/cython.rs 的 SourceMap：把「生成的 C 文件行号」映回「.pyx 文件 + 行号」"""

    def __init__(self, contents):
        self.keys = []          # 0-based 行下标 → 标记
        self.vals = []
        line_count = 0
        for lineno, line in enumerate(contents.splitlines()):
            m = MARKER_RE.match(line)
            if m:
                filename, cython_line = m.group(1), int(m.group(2))
                self.keys.append(lineno)
                self.vals.append((filename, cython_line))
            line_count += 1
        # 哨兵：文件末尾之后一格，值 ("", 0) 表示 EOF
        self.keys.append(line_count + 1)
        self.vals.append(("", 0))

    def lookup(self, lineno):
        """对应 range(..lineno).next_back()：取 **严格小于** lineno 的最大键"""
        i = bisect.bisect_left(self.keys, lineno) - 1
        if i < 0:
            return None
        fn, ln = self.vals[i]
        if ln == 0:             # 命中 EOF 哨兵
            return None
        return fn, ln


def ignore_frame(name):
    """cython.rs：这些是 Cython 的调用胶水，不是用户代码"""
    return name in ("__Pyx_PyFunction_FastCallDict", "__Pyx_PyObject_CallOneArg",
                    "__Pyx_PyObject_Call", "__pyx_FusedFunction_call")


def demangle(name):
    """cython.rs 的 demangle：切掉前缀，再按 `_<长度><名字>` 逐段剥模块/文件/类名"""
    prefixes = ["__pyx_fuse_1_0__pyx_pw", "__pyx_fuse_0__pyx_f",
                "__pyx_fuse_1__pyx_f", "__pyx_pf", "__pyx_pw",
                "__pyx_f", "___pyx_f", "___pyx_pw"]
    hit = None
    for p in prefixes:
        if name.startswith(p):
            hit = p
            break
    if hit is None:
        return name
    current = name[len(hit):]
    nxt = current
    while True:
        if not nxt.startswith("_"):
            break
        digit_index = 1
        for ch in nxt[1:]:
            if not ch.isdigit() or not ch.isascii():
                break
            digit_index += 1
        if digit_index == 1:
            break
        digits = int(nxt[1:digit_index])
        current = nxt[digit_index:]
        if digits + digit_index >= len(current):
            break
        nxt = nxt[digits + digit_index:]
    return current


# ------------------------------------------------------ 采样：Python 栈 vs 原生栈

class Frame:
    def __init__(self, name, filename, line, native=False):
        self.name, self.filename, self.line, self.native = name, filename, line, native


def python_only_samples(frames):
    """不开 --native：只能沿 PyFrameObject 的 back 链走，原生帧整段看不见"""
    return [f for f in frames if not f.native]


def native_samples(frames):
    """开 --native：原生帧进栈，但需要符号才能有行号"""
    out = []
    for f in frames:
        if ignore_frame(f.name):
            continue            # Cython 调用胶水被摘掉
        out.append(f)
    return out


def resolve_cython_file(cpp_filename, cython_filename, module, exists):
    """cython.rs：把 C 文件名换成 .pyx/.pxd 扩展名，且必须真的存在"""
    if "." in cython_filename:
        ext = cython_filename.rsplit(".", 1)[1]
        base = cpp_filename.rsplit(".", 1)[0] + "." + ext
        if base.endswith(cython_filename) and base in exists:
            return base
    if module:
        return cython_filename if cython_filename in exists else cython_filename
    return cython_filename


# ------------------------------------------------------ --native 的平台支持

# README 的支持表：只有 Linux(x86-64/ARM/Aarch64) 与 Windows(x86-64)
NATIVE_SUPPORT = {("Linux", "x86-64"), ("Linux", "ARM"), ("Linux", "Aarch64"),
                  ("Windows", "x86-64")}


def native_supported(os_name, arch):
    return (os_name, arch) in NATIVE_SUPPORT


# ---------------------------------------------------------------- 自检
PASS = 0


def ok(cond, msg):
    global PASS
    assert cond, "FAIL: " + msg
    PASS += 1


C_FILE = '\n'.join([
    '/* Generated by Cython 3.0.10 */',
    '/* "fast.pyx":10',          # 0-based 1  → .pyx:10 从第 2 行起生效
    'static int __pyx_f_4fast_compute(void) {',
    '  int i;',
    '/* "fast.pyx":11',          # 0-based 4  → .pyx:11
    '  for (i = 0; i < 10; i++) {',
    '/* "helpers.pyx":3',        # 0-based 6  → helpers.pyx:3
    '    do_work(i);',
    '  }',
    '}',
])


def check_source_map():
    sm = SourceMap(C_FILE)
    ok(sm.lookup(1) is None, "第 1 行在第一个标记之前 ⇒ 无映射")
    ok(sm.lookup(2) == ("fast.pyx", 10), "标记所在行本身即生效（键是 0-based 下标）")
    ok(sm.lookup(3) == ("fast.pyx", 10), "标记之后继续沿用，直到下一个标记")
    ok(sm.lookup(5) == ("fast.pyx", 11), "新标记覆盖旧标记")
    ok(sm.lookup(7) == ("helpers.pyx", 3), "跨文件标记也能正确切换")
    ok(sm.lookup(10) == ("helpers.pyx", 3), "文件末行仍落在最后一个标记上")
    # 哨兵键是 line_count+1 = 11，而 range 是右开的 ⇒ 必须 lineno ≥ 12 才读得到哨兵
    ok(sm.lookup(11) == ("helpers.pyx", 3), "lineno=11 时哨兵键自己被右开区间排除")
    ok(sm.lookup(12) is None, "lineno=12 才命中 EOF 哨兵，返回 None")
    ok(sm.lookup(999) is None, "远超末尾同样是 None")


def check_marker_regex():
    ok(MARKER_RE.match('/* "a.pyx":12') is not None, "最简标记可匹配")
    ok(MARKER_RE.match('   /* "pkg/mod.pyx":7') is not None, "行首空白允许")
    ok(MARKER_RE.match('/* "a.pyx":12').group(2) == "12", "行号是第二组")
    ok(MARKER_RE.match('// "a.pyx":12') is None, "必须是 /* 注释形式")
    ok(MARKER_RE.match('/* "nodot":12') is None, "文件名必须带扩展名（.+ \\. .+）")


def check_demangle():
    """这四条正是 cython.rs 单元测试里的官方向量"""
    ok(demangle("__pyx_pf_8implicit_4_als_30_least_squares_cg") == "_least_squares_cg",
       "官方向量 1：模块+文件+类名前缀被剥掉")
    ok(demangle("__pyx_pw_8implicit_4_als_5least_squares_cg") == "least_squares_cg",
       "官方向量 2：pw 前缀")
    ok(demangle("__pyx_fuse_1_0__pyx_pw_8implicit_4_als_31_least_squares_cg") == "_least_squares_cg",
       "官方向量 3：fuse 前缀")
    ok(demangle("__pyx_f_6mtrand_cont0_array") == "mtrand_cont0_array",
       "官方向量 4：numpy mtrand")
    ok(demangle("PyEval_EvalFrameDefault") == "PyEval_EvalFrameDefault",
       "非 Cython 符号原样返回")


def check_ignore_frame():
    ok(ignore_frame("__pyx_FusedFunction_call"), "fused function 胶水被忽略")
    ok(ignore_frame("__Pyx_PyObject_Call"), "Cython 调用胶水被忽略")
    ok(not ignore_frame("__pyx_f_4fast_compute"), "真正的 Cython 用户函数保留")


def check_native_vs_python():
    frames = [
        Frame("__pyx_f_4fast_compute", "fast.c", 900, native=True),
        Frame("__pyx_FusedFunction_call", "fast.c", 500, native=True),
        Frame("__Pyx_PyObject_Call", "fast.c", 300, native=True),
        Frame("worker", "app.py", 42, native=False),
        Frame("main", "app.py", 10, native=False),
    ]
    py = python_only_samples(frames)
    ok([f.name for f in py] == ["worker", "main"],
       "不开 --native：只剩 Python 帧，整段 Cython 计算被算进 Python 帧的自身耗时")

    nat = native_samples(frames)
    ok([f.name for f in nat] == ["__pyx_f_4fast_compute", "worker", "main"],
       "开 --native：原生帧进栈，且胶水帧被摘掉")

    sm = SourceMap(C_FILE)
    top = nat[0]
    ok(sm.lookup(top.line) is None, "行号落在生成 C 文件之外 ⇒ 无法还原 .pyx 行号（缺符号/缺 C 文件）")


def check_platform():
    ok(native_supported("Linux", "x86-64"), "Linux x86-64 支持 --native")
    ok(native_supported("Linux", "Aarch64"), "Linux Aarch64 支持 --native")
    ok(native_supported("Windows", "x86-64"), "Windows x86-64 支持 --native")
    ok(not native_supported("OSX", "x86-64"), "macOS 表里是空的 ⇒ 不支持 --native")
    ok(not native_supported("Linux", "i686"), "i686 一整行都是空的")
    ok(not native_supported("FreeBSD", "x86-64"), "FreeBSD 不支持")


def check_resolve():
    exists = {"build/fast.pyx"}
    ok(resolve_cython_file("build/fast.c", "fast.pyx", "fast", exists) == "build/fast.pyx",
       "C 文件名换成 .pyx 扩展名后存在 ⇒ 用真实路径")
    ok(resolve_cython_file("build/fast.cpp", "missing.pyx", None, exists) == "missing.pyx",
       "找不到就原样返回（py-spy 不会凭空造路径）")


if __name__ == "__main__":
    for fn in (check_marker_regex, check_source_map, check_demangle,
               check_ignore_frame, check_native_vs_python, check_platform,
               check_resolve):
        fn()
    print("PASS %d assertions" % PASS)
