"""gRPC 状态码与重试语义的最小可运行模型。

口径来源（本轮实读 grpc.io/docs/guides/status-codes/，74 091 字节）：
  - 所有 RPC 都会返回一个 status（整数 code + 字符串描述）；应用 SHOULD 只用下面这些值。
  - 库只会产生**其中一部分**code；列出的 7 个**从不由库生成，只由用户代码产生**：
    INVALID_ARGUMENT / NOT_FOUND / ALREADY_EXISTS / FAILED_PRECONDITION /
    ABORTED / OUT_OF_RANGE / DATA_LOSS（另见下表的 UNAUTHENTICATED 不在其中）。
    ⇒ 应用看到这 7 个码时可以确信"这确实是服务端业务返回的"。
  - 判定准则（原文 guidelines）：
      (a) 客户端**只重试失败的那次调用**即可 ⇒ UNAVAILABLE
      (b) 客户端应在**更高层**重试（例如 test-and-set 失败要重跑 read-modify-write）⇒ ABORTED
      (c) 系统状态被显式修好之前**不要重试** ⇒ FAILED_PRECONDITION
  - NOT_FOUND 与 PERMISSION_DENIED 的分工：
    对**整类用户**拒绝（灰度未放量、未公开的 allowlist）可用 NOT_FOUND；
    对**同类中的部分用户**拒绝（基于用户的访问控制）MUST 用 PERMISSION_DENIED。
  - PERMISSION_DENIED 不得用于「资源耗尽」（用 RESOURCE_EXHAUSTED）；
    不得用于「无法识别调用方」（用 UNAUTHENTICATED）。
  - OUT_OF_RANGE 与 INVALID_ARGUMENT：前者的问题会随系统状态变化而消失，
    遍历场景推荐用 OUT_OF_RANGE（更具体）来判定"结束了"。
  - DEADLINE_EXCEEDED 对改变状态的操作**可能返回成功之外的语义**：
    操作也许已经成功，只是响应被延迟到 deadline 之后。

运行：python grpcstatus.py
"""

CODES = [
    ("OK", 0),
    ("CANCELLED", 1),
    ("UNKNOWN", 2),
    ("INVALID_ARGUMENT", 3),
    ("DEADLINE_EXCEEDED", 4),
    ("NOT_FOUND", 5),
    ("ALREADY_EXISTS", 6),
    ("PERMISSION_DENIED", 7),
    ("RESOURCE_EXHAUSTED", 8),
    ("FAILED_PRECONDITION", 9),
    ("ABORTED", 10),
    ("OUT_OF_RANGE", 11),
    ("UNIMPLEMENTED", 12),
    ("INTERNAL", 13),
    ("UNAVAILABLE", 14),
    ("DATA_LOSS", 15),
    ("UNAUTHENTICATED", 16),
]

NAME_TO_ID = dict(CODES)
ID_TO_NAME = {i: n for n, i in CODES}

# "The following status codes are never generated by the library, only by user code"
APP_ONLY = frozenset([
    "INVALID_ARGUMENT", "NOT_FOUND", "ALREADY_EXISTS", "FAILED_PRECONDITION",
    "ABORTED", "OUT_OF_RANGE", "DATA_LOSS",
])

# §FAILED_PRECONDITION 的 (a)(b)(c) 三条判定准则
RETRY_HINT = {
    "UNAVAILABLE": "retry-call",        # (a) 只重试失败的那次调用
    "ABORTED": "retry-higher-level",    # (b) 在更高层重试
    "FAILED_PRECONDITION": "no-retry",  # (c) 状态被显式修好前不重试
}


def code_id(name):
    return NAME_TO_ID.get(name)


def code_name(identifier):
    return ID_TO_NAME.get(identifier)


def is_app_only(name):
    """是否属于"库永远不会生成"的那批（看到即可确信来自服务端业务）。"""
    return name in APP_ONLY


def library_generated(name):
    """反向集合：除去 7 个应用专属码，其余都可能由库产生。"""
    return name in NAME_TO_ID and name not in APP_ONLY


def retry_hint(name):
    """返回 retry-call / retry-higher-level / no-retry，没有准则时返回 None。"""
    return RETRY_HINT.get(name)


def classify_denial(scope):
    """NOT_FOUND 与 PERMISSION_DENIED 的分工。

    scope="whole-class"  → 对整类用户不可见 ⇒ NOT_FOUND
    scope="within-class" → 同类中的部分用户被拒 ⇒ PERMISSION_DENIED
    """
    if scope == "whole-class":
        return "NOT_FOUND"
    if scope == "within-class":
        return "PERMISSION_DENIED"
    return None


def classify_auth_failure(reason):
    """PERMISSION_DENIED / RESOURCE_EXHAUSTED / UNAUTHENTICATED 的分工。"""
    if reason == "quota-exhausted":
        return "RESOURCE_EXHAUSTED"
    if reason == "cannot-identify-caller":
        return "UNAUTHENTICATED"
    if reason == "no-permission":
        return "PERMISSION_DENIED"
    return None


def classify_bad_range(kind):
    """INVALID_ARGUMENT 与 OUT_OF_RANGE 的分工。"""
    if kind == "outside-representable":
        return "INVALID_ARGUMENT"
    if kind == "beyond-current-size":
        return "OUT_OF_RANGE"
    return None


def is_success(name):
    return name == "OK"
